# Generated by Django 5.2.8 on 2025-11-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
