# Generated by Django 5.2.8 on 2026-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
