# Generated by Django 5.2.8 on 2026-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
