# Generated by Django 5.2.8 on 2025-12-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('city', '0002_alter_city_options_township'),
        ('country', '0004_currency_country_default_currency'),
        ('property', '0001_initial'),
        ('property_type', '0002_alter_propertytype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='amenities.amenity'),
        ),
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('sqft', 'Sqft'), ('acre', 'Acre'), ('sqm', 'm²')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.currency'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property_type.propertytype'),
        ),
        migrations.AddField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='city.city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='country.country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='property',
            name='township',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='city.township'),
        ),
    ]
