# Generated by Django 5.2.8 on 2025-12-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_name'),
        ('owners', '0001_initial'),
        ('property', '0002_alter_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='advertiser',
        ),
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='companies.company'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='owners.owner'),
        ),
    ]
