# Generated by Django 5.2.8 on 2026-01-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_advertiser_property_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='installment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='price_frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
