# Generated by Django 5.2.8 on 2026-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_contract_duration_property_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='co_brokerage',
            field=models.BooleanField(default=False, help_text='Enable if another agent is involved and a fee must be shared.', verbose_name='Co-brokerage'),
        ),
    ]
