# Generated by Django 5.2.8 on 2026-01-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_co_brokerage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='maplink',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='yearbuilt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
