# Generated by Django 5.2.8 on 2025-12-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
