# Generated by Django 5.2.8 on 2025-11-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Subscription Active)'), ('REJECTED', 'Rejected / Failed Payment')], default='PENDING', max_length=10),
        ),
    ]
