# Generated by Django 5.2.8 on 2025-11-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Subscription Active)'), ('REJECTED', 'Rejected / Failed Payment'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
    ]
