# Generated by Django 5.2.8 on 2025-11-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_end_date_order_start_date_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_duration_type',
            field=models.CharField(default='MONTH', editable=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='package_max_properties',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='order',
            name='package_name',
            field=models.CharField(default='MONTH', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
