# Generated by Django 5.2.8 on 2025-12-15 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_package_duration_type_and_more'),
        ('package', '0005_alter_package_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='package_duration_type',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='package_duration_months',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='package.package'),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_max_properties',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
