# Generated by Django 5.2.8 on 2026-01-03 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_buyer_budget_max_alter_buyer_budget_min'),
        ('companies', '0004_alter_company_name'),
        ('property', '0005_property_co_brokerage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('call', 'Call'), ('visit', 'Visit / Meeting'), ('message', 'SMS / Text Message'), ('email', 'Email'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('note', 'Note')], max_length=20)),
                ('content', models.TextField(blank=True, help_text='Optional details about this communication', null=True)),
                ('reminder_date', models.DateTimeField(blank=True, help_text='Optional follow-up reminder', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Staff responsible for this log', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_communications', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='buyers.buyer')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communications', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property')),
            ],
        ),
    ]
