# Generated by Django 5.2.8 on 2026-01-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_communicationlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='buyer',
            name='buyers_buye_phone_446a66_idx',
        ),
        migrations.RemoveIndex(
            model_name='buyer',
            name='buyers_buye_email_a52253_idx',
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Optional follow-up time', null=True),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='reminder_date',
            field=models.DateField(blank=True, help_text='Optional follow-up date', null=True),
        ),
    ]
