# Generated by Django 5.2.8 on 2025-11-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price (0.00 for free plan)', max_digits=6)),
                ('max_properties', models.PositiveIntegerField(help_text='Maximum number of active properties allowed for this plan. Use 0 for unlimited.')),
                ('is_default', models.BooleanField(default=False, help_text='If checked, this is the free plan automatically assigned to new users.')),
            ],
            options={
                'verbose_name_plural': 'Packages (Subscription Plans)',
            },
        ),
    ]
