# Generated by Django 5.2.8 on 2025-11-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Monthly price in Kyat (0 for free plan)', max_digits=8),
        ),
    ]
