# Generated by Django 5.2.8 on 2025-11-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration_type',
            field=models.CharField(choices=[('MONTH', 'Monthly'), ('YEAR', 'Yearly')], default='MONTH', help_text='Type of subscription duration', max_length=5),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Price in Kyat (0 for free plan)', max_digits=8),
        ),
    ]
