# Generated by Django 5.2.8 on 2025-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_package_duration_type_alter_package_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['duration_months']},
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_type',
        ),
        migrations.AddField(
            model_name='package',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_properties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
