# Generated by Django 5.2.8 on 2025-12-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_package_options_remove_package_duration_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
    ]
