# Generated by Django 5.2.8 on 2025-12-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'Property Type', 'verbose_name_plural': 'Property Types'},
        ),
    ]
