# Generated by Django 5.2.8 on 2026-01-06 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_company_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('down_payment', 'Down Payment'), ('installment', 'Installment'), ('milestone', 'Milestone'), ('bank_loan', 'Bank Loan'), ('balloon', 'Balloon Payment'), ('full_payment', 'Full Payment')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('months', models.PositiveIntegerField(blank=True, null=True)),
                ('due_after_month', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='paymentplans.paymentplan')),
            ],
        ),
    ]
